# Generated by Django 4.2 on 2025-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Drive System',
                'verbose_name_plural': 'Drive Systems',
                'db_table': 'drive_system',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EngineType',
                'verbose_name_plural': 'EngineTypes',
                'db_table': 'engine_type',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('engine_displacement', models.IntegerField()),
                ('power', models.IntegerField()),
                ('number_of_gears', models.IntegerField(blank=True, null=True)),
                ('brakes', models.IntegerField(max_length=100)),
                ('suspension', models.IntegerField(max_length=100)),
                ('weight', models.IntegerField()),
                ('length', models.FloatField()),
                ('seat_height', models.IntegerField()),
                ('wheelbase', models.IntegerField()),
                ('top_speed', models.IntegerField()),
                ('description', models.TextField()),
                ('image_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
                'db_table': 'motorcycle',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'MotorcycleType',
                'verbose_name_plural': 'MotorcycleTypes',
                'db_table': 'motorcycle_type',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
                'db_table': 'transmission_type',
            },
        ),
    ]
