# Generated by Django 4.2 on 2025-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MotorcycleBrand',
                'verbose_name_plural': 'MotorcycleBrands',
                'db_table': 'motorcycle_brand',
            },
        ),
    ]
