# Generated by Django 4.2 on 2025-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_motorcyclebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='brakes',
            field=models.CharField(max_length=100),
        ),
    ]
