# Generated by Django 4.2 on 2025-08-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_motorcycle_brakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='drive_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.drivesystem'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.enginetype'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.transmissiontype'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.motorcyclebrand'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='suspension',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.motorcycletype'),
        ),
    ]
